### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jjpe** [ProgrammingLife3/ProgrammingLife3#17]
Hi team 3,

I have feedback ready for you. What email address(es) should I send it to?

Cheers,
Joey

**Comment by borismattijssen** [comment]
borismattijssen@gmail.com
k.wendel@student.tudelft.nl
s.smulders@student.tudelft.nl
mathieupost@gmail.com
tombrouws@icloud.com

**Comment by Delfil** [comment]
Our names, student numbers and email addresses are found in our readme.md
